spring.application.name=my-books

server.port=8081

# DataBase
spring.datasource.url=jdbc:mysql://localhost:3306/mybooksDB_in5av?createDatabaseIfNotExist=true
spring.datasource.username=IN5AV
spring.datasource.password=!+admin5av

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect